### ISSUE TITLE
Zipcode_Info documentation

### ISSUE THREAD

**Issue by audiracmichelle** [NSAPH/handbook#49]

**Comment by keziatesiman** [comment]
Steps: 
1. Add a section in https://nsaph.info/data.html?highlight=shapefile called "Zipcode_info"
2. Delete zip_shape_files
3. Make documentation that looks like the one in PM2.5, Ozone, NO2
add: https://www.overleaf.com/project/6248df38346ed665a2b1fb08 as description
Repository: [https://github.com/NSAPH/National-Causal-Analysis/tree/master/Exposures/code/yaguang_pm25_code](https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_NSAPH_National-2DCausal-2DAnalysis_tree_master_Exposures_code_yaguang-5Fpm25-5Fcode&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=dMXQpeK5k-KBFKnGKL0ohCrS2jfen_3io41lY2cHQCs&m=xIzNtW0lkE0uTZ4NBOePdtPeiJNlc_rIMVgEcDBmk_5eFikyi__pHJVdLlc31Tu0&s=wLUdXNx_47B4XcZa8NFsc-9E78-HtaEDGczKWK7wXrc&e=)

**Comment by keziatesiman** [comment]
https://github.com/NSAPH/handbook/pull/51
